Description: Email service Go application deployed to AWS Lambda

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: email-service.zip
      Handler: main
      Runtime: go1.18
      Timeout: 300

  APIGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Email service Go application deployed to AWS Lambda
      Name: EmailService

  APIGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref APIGatewayRestApi
      StageName: Prod

  APIGatewayRestApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      Path: /
      RestApiId: !Ref APIGatewayRestApi
      StageName: Prod

  APIGatewayRestApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGatewayRestApi}/*/POST/"

Outputs:
  APIGatewayEndpoint:
    Description: The URL of the API Gateway endpoint
    Value: !Sub "https://${APIGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"